export const HOME = 'HOME'
export const ADD_DECK = 'ADD_DECK'
export const ADD_CARD = 'ADD_CARD'
export const LOAD_DECK = 'LOAD_DECK'
export const START_QUIZ = 'START_QUIZ'
export const UPDATE_QUIZ_SIZE = 'UPDATE_QUIZ_SIZE'
